#!/bin/sh
OUTPUTFILE=/tmp/hcserver.$$.out
ERRFILE=/tmp/hc_err_file.tmp
exec /home/rwalsh10/my_scripts/new_hc.sh |tee ${OUTPUTFILE}
(
echo "From: richard_walsh@optum.com"
echo "To: richard_walsh@optum.com"
echo "MIME-Version: 1.0"
echo "Subject: Health Check Output `date +%m-%d-%Y:%H:%M`"
echo "Content-Type: text/html"
echo "<FONT FACE='COURIER NEW' SIZE='3'><PRE>"
echo "The ERR! results are based on the following criterea:\n"
echo "FS = Filesystems => 85% Full\n"
echo "MEM = Memory utilization => 95%\n"
echo "SWAP = Swap utilization => 80%\n"
echo "CPU = 5 minute load average/number of cores => 90%\n\n"
cat ${OUTPUTFILE}
echo "\n"
if [ -f ${ERRFILE} ]; then
	cat ${ERRFILE}
	rm -f ${ERRFILE}
fi
echo "</PRE></FONT>" ) | sendmail -t
rm -f ${OUTPUTFILE}
