#!/bin/sh
#
# Script to update password on multiple systems
# * Only good for new passwords *
#
#
if [ $# != 1 ] ; then
	echo "USAGE: ${0} <host_list_file>"
	exit 0
fi

echo "Enter your user name: "
        read USER
echo "Enter your old password: "
	read OLD_PASS
echo "Enter desired new password: "
	read NEW_PASS

HOST_LIST=`cat $1`

for HOST in ${HOST_LIST}
	do
	# Check if the server is reachable first
		ping -c 1 ${HOST} &>/dev/null
		if [ $? != 0 ] ; then
			continue
		fi
		
	echo "Changing password for ${HOST}"
		{
		/bin/expect - << EOF
		spawn ssh -q -l ${USER} -oStrictHostKeyChecking=no -oConnectTimeout=10 ${HOST}
		expect "assword:"
		send "${OLD_PASS}\r";
		expect "assword:"
		send "${OLD_PASS}\r";
		expect "assword:"
		send "${NEW_PASS}\r";
		expect ":"
		send "${NEW_PASS}\r";
		sleep 5
		EOF
		}
	echo "Completed ${HOST}"
done
