#!/bin/sh
#
# Run a ping check against a
# list of servers.
#
trap "exit" INT

if [ $# != 1 ] ; then
	echo "USAGE: ${0} <host_list_file>"
	exit 0
fi

HOSTLIST=`cat $1`

for HOST in ${HOSTLIST}
        do
        printf "${HOST}: "
        ping -c 1 ${HOST} >/dev/null 2>&1
        if [ $? = 0 ] ; then
        	printf "Reachable\n"
        else
        	printf "Not reachable\n"
        fi
	done
